name: Code Quality Control

on:
  pull_request:
    branches: [main]
  push:
    branches: ['*']

jobs:
  quality-check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit black pylint

    - name: Run pylint
      run: |
        pylint --rcfile=.pylintrc --fail-under=6.5 fastvpinns
    
    - name: Run black
      run: |
        black --check fastvpinns
